[package]
name = "zsp2"
version = "0.5.1"
authors = ["zzzzzzzzzzz <zzzzzzzzzzzgg@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zhscript2 = {version = "0.5.1", path = "../zhscript2-rust", features = ["thread"]}
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-files = "0.2.1"
lazy_static = "1.4.0"
url = "2.1.1"
regex = "1.3.4"
rand = "0.7.3"
